# Generated by Django 5.2.13 on 2026-05-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAYMENT_PENDING', 'Payment pending'), ('PAID', 'Paid'), ('PAYMENT_FAILED', 'Payment failed'), ('PAYMENT_CANCELLED', 'Payment cancelled'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=20),
        ),
    ]
