# Generated by Django 5.2.13 on 2026-05-06 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_checkoutsession_status'),
        ('receipts', '0002_alter_receipt_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='erp_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='erp_status',
            field=models.CharField(choices=[('NOT_SYNCED', 'Not synced'), ('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed'), ('RETRY_REQUIRED', 'Retry required')], default='NOT_SYNCED', max_length=20),
        ),
        migrations.AddField(
            model_name='receipt',
            name='erp_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['erp_status', 'created_at'], name='receipts_re_erp_sta_770f1d_idx'),
        ),
    ]
