# Generated by Django 5.2.13 on 2026-05-06 06:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('checkout', '0003_checkoutitem_confidence_checkoutitem_review_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightedItemEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('weight_unit', models.CharField(choices=[('KG', 'Kilogram'), ('GRAM', 'Gram')], default='KG', max_length=10)),
                ('weight_source', models.CharField(choices=[('MANUAL', 'Manual'), ('OCR', 'OCR')], default='MANUAL', max_length=10)),
                ('raw_ocr_text', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkout_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weighted_entry', to='checkout.checkoutitem')),
                ('checkout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weighted_entries', to='checkout.checkoutsession')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weighted_item_entries', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weighted_entries', to='catalog.product')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['checkout_session', 'created_at'], name='weighted_it_checkou_0a58a1_idx'), models.Index(fields=['product', 'created_at'], name='weighted_it_product_be4fae_idx'), models.Index(fields=['weight_source', 'created_at'], name='weighted_it_weight__a1f99c_idx')],
            },
        ),
    ]
