# Generated by Django 5.2.13 on 2026-05-05 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('checkout', '0002_alter_checkoutitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('model_path', models.CharField(blank=True, max_length=1024)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['is_active', 'created_at'], name='vision_mode_is_acti_f6fd2b_idx'), models.Index(fields=['name', 'version'], name='vision_mode_name_f9819c_idx')],
            },
        ),
        migrations.CreateModel(
            name='DetectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='checkout_frames/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_runs', to='checkout.checkoutsession')),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_runs', to='vision.modelversion')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DetectedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('bbox_x1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bbox_y1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bbox_x2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bbox_y2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('review_status', models.CharField(choices=[('AUTO_ACCEPTED', 'Auto accepted'), ('NEEDS_REVIEW', 'Needs review'), ('REJECTED_LOW_CONFIDENCE', 'Rejected: low confidence'), ('UNKNOWN_CLASS', 'Unknown class')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_objects', to='catalog.product')),
                ('detection_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='vision.detectionrun')),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['detection_run', 'created_at'], name='vision_dete_detecti_2cc9c5_idx'), models.Index(fields=['class_name'], name='vision_dete_class_n_865695_idx'), models.Index(fields=['review_status'], name='vision_dete_review__76c1fb_idx'), models.Index(fields=['matched_product'], name='vision_dete_matched_a022a2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='detectionrun',
            index=models.Index(fields=['checkout_session', 'created_at'], name='vision_dete_checkou_c8ac9e_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionrun',
            index=models.Index(fields=['status', 'created_at'], name='vision_dete_status_a390cf_idx'),
        ),
    ]
