# Generated by Django 5.2.13 on 2026-05-05 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedobject',
            name='detection_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_objects', to='vision.detectionrun'),
        ),
    ]
