# Generated by Django 5.1.15 on 2026-05-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vision", "0003_cameraconfig"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cameraconfig",
            new_name="vision_came_termina_b3b4a3_idx",
            old_name="vision_came_termina_idx",
        ),
        migrations.RenameIndex(
            model_name="cameraconfig",
            new_name="vision_came_termina_81f14d_idx",
            old_name="vision_came_termina_role_idx",
        ),
        migrations.AddField(
            model_name="cameraconfig",
            name="mock_current_index",
            field=models.IntegerField(default=0),
        ),
    ]
