# Generated by Django 5.1.15 on 2026-05-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vision", "0004_add_mock_current_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cameraconfig",
            name="mock_current_index",
        ),
        migrations.AddField(
            model_name="cameraconfig",
            name="mock_video_path",
            field=models.CharField(
                blank=True,
                help_text="Path to a looping .mp4 video file (used when source_type=MOCK_VIDEO).",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cameraconfig",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("MOCK_FOLDER", "Mock Folder (images)"),
                    ("MOCK_VIDEO", "Mock Video (looping .mp4)"),
                    ("USB", "USB Camera"),
                    ("NETWORK", "Network / IP Camera"),
                ],
                default="MOCK_FOLDER",
                max_length=16,
            ),
        ),
    ]
