# Generated by Django 5.1.15 on 2026-05-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vision", "0005_add_mock_video_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cameraconfig",
            name="mock_video_path",
        ),
        migrations.AddField(
            model_name="cameraconfig",
            name="snapshot_url",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="cameraconfig",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("MOCK_FOLDER", "Mock Folder"),
                    ("USB", "USB Camera"),
                    ("NETWORK", "Network / IP Camera"),
                ],
                default="MOCK_FOLDER",
                max_length=16,
            ),
        ),
    ]
