# Generated by Django 5.2.13 on 2026-05-06 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('receipts', '0003_receipt_erp_reference_receipt_erp_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('product_names_correct', models.BooleanField(default=True)),
                ('quantities_correct', models.BooleanField(default=True)),
                ('prices_correct', models.BooleanField(default=True)),
                ('subtotals_correct', models.BooleanField(default=True)),
                ('total_correct', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_evaluations', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='receipts.receipt')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['is_correct', 'created_at'], name='audit_recei_is_corr_0cba33_idx'), models.Index(fields=['total_correct', 'created_at'], name='audit_recei_total_c_5dd9d6_idx')],
            },
        ),
    ]
