# Generated by Django 5.2.13 on 2026-05-06 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('receipts', '0002_alter_receipt_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('PRODUCT', 'Product'), ('RECEIPT', 'Receipt'), ('PAYMENT', 'Payment'), ('TRANSACTION', 'Transaction')], max_length=20)),
                ('object_id', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('SYNC_PRODUCTS', 'Sync products'), ('PUSH_RECEIPT', 'Push receipt'), ('RETRY_SYNC', 'Retry sync')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('erp_system', models.CharField(default='ODOO', max_length=50)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['object_type', 'created_at'], name='erp_erpsync_object__f4eb44_idx'), models.Index(fields=['action', 'created_at'], name='erp_erpsync_action_26bda0_idx'), models.Index(fields=['status', 'created_at'], name='erp_erpsync_status_2a96e0_idx'), models.Index(fields=['erp_system', 'created_at'], name='erp_erpsync_erp_sys_4ea940_idx'), models.Index(fields=['object_id'], name='erp_erpsync_object__4fc2c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ERPProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_system', models.CharField(default='ODOO', max_length=50)),
                ('erp_product_id', models.CharField(max_length=100)),
                ('erp_product_name', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_mappings', to='catalog.product')),
            ],
            options={
                'ordering': ('erp_system', 'product_id'),
                'indexes': [models.Index(fields=['erp_system', 'erp_product_id'], name='erp_erpprod_erp_sys_796825_idx'), models.Index(fields=['product', 'erp_system'], name='erp_erpprod_product_960383_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'erp_system'), name='unique_product_erp_system_mapping')],
            },
        ),
        migrations.CreateModel(
            name='ERPReceiptMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_system', models.CharField(default='ODOO', max_length=50)),
                ('erp_receipt_id', models.CharField(blank=True, max_length=100, null=True)),
                ('erp_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed'), ('RETRY_REQUIRED', 'Retry required')], default='PENDING', max_length=20)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_mappings', to='receipts.receipt')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['erp_system', 'sync_status', 'created_at'], name='erp_erprece_erp_sys_87ae4c_idx'), models.Index(fields=['receipt', 'erp_system'], name='erp_erprece_receipt_0c0c39_idx')],
                'constraints': [models.UniqueConstraint(fields=('receipt', 'erp_system'), name='unique_receipt_erp_system_mapping')],
            },
        ),
    ]
