# Generated by Django 5.2.13 on 2026-05-06 06:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0004_alter_checkoutsession_status'),
        ('receipts', '0002_alter_receipt_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MOBILE_MONEY', 'Mobile money'), ('BANK_TRANSFER', 'Bank transfer'), ('DEMO', 'Demo')], default='DEMO', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('provider_name', models.CharField(default='SIMULATED', max_length=100)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkout_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='checkout.checkoutsession')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='receipts.receipt')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['receipt', 'created_at'], name='payments_pa_receipt_03d121_idx'), models.Index(fields=['checkout_session', 'created_at'], name='payments_pa_checkou_3068c7_idx'), models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'), models.Index(fields=['method', 'created_at'], name='payments_pa_method_5225c8_idx')],
            },
        ),
    ]
