# Generated by Django 5.2.13 on 2026-05-05 06:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CheckoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('VISION', 'Vision'), ('BARCODE', 'Barcode'), ('WEIGHTED', 'Weighted')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_items', to='catalog.product')),
                ('checkout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.checkoutsession')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='checkoutsession',
            index=models.Index(fields=['status', 'created_at'], name='checkout_ch_status_c6ce5a_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutsession',
            index=models.Index(fields=['cashier', 'created_at'], name='checkout_ch_cashier_18d083_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutitem',
            index=models.Index(fields=['checkout_session', 'status'], name='checkout_ch_checkou_d86f45_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutitem',
            index=models.Index(fields=['product'], name='checkout_ch_product_36eb53_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutitem',
            index=models.Index(fields=['source'], name='checkout_ch_source_408c71_idx'),
        ),
    ]
