# Generated by Django 5.2.13 on 2026-05-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutitem',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('NEEDS_REVIEW', 'Needs review'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=20),
        ),
    ]
