# Generated by Django 5.2.13 on 2026-05-05 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_checkoutitem_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutitem',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Optional confidence score for VISION items (0..1).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='checkoutitem',
            name='review_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('NEEDS_REVIEW', 'Needs review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('REPLACED', 'Replaced')], default='NOT_REQUIRED', max_length=20),
        ),
        migrations.CreateModel(
            name='CheckoutCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction_type', models.CharField(choices=[('ACCEPT_ITEM', 'Accept item'), ('REJECT_ITEM', 'Reject item'), ('REPLACE_PRODUCT', 'Replace product'), ('CHANGE_QUANTITY', 'Change quantity')], max_length=32)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='checkout.checkoutitem')),
                ('checkout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='checkout.checkoutsession')),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['checkout_session', 'created_at'], name='checkout_ch_checkou_0f487f_idx'), models.Index(fields=['correction_type', 'created_at'], name='checkout_ch_correct_011fed_idx')],
            },
        ),
    ]
