# Generated by Django 5.2.13 on 2026-05-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_checkoutitem_confidence_checkoutitem_review_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CONFIRMED', 'Confirmed'), ('PAYMENT_PENDING', 'Payment pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20),
        ),
    ]
