# Generated by Django 5.2.13 on 2026-05-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_checkoutsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
